name: Build

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - uses: hmarr/debug-action@v2

      # Install dependencies
      - run: npm ci

      # Build and output webpack stats to artifacts/webpack-stats.json
      - run: npm run build --if-present

      # Send webpack stats and build information to RelativeCI
      - name: Send webpack stats to RelativeCI
        uses: relative-ci/agent-action@c6f931bc13c5a696a8af406ffef90e6395d0c92c
        with:
          webpackStatsFile: ./artifacts/webpack-stats.json
          key: ${{ secrets.RELATIVE_CI_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug: true
